spring:
  application:
    name: fintrackr-backend
  datasource:
    url: ${postgres_url}
    username: ${postgres_user}
    password: ${postgres_passwd}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Enable Swagger UI at /swagger-ui.html
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
