spring:
  application:
    name: fintrackr-backend
  datasource:
    url: postgresql://gautam_govind:dlKXsPQcQFERvRUjI2rCuBp9qL6m5QGz@dpg-d0o2d08dl3ps73a6tppg-a/fintrackr_backend_db
    username: gautam_govind
    password: dlKXsPQcQFERvRUjI2rCuBp9qL6m5QGz
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Enable Swagger UI at /swagger-ui.html
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
